[project]
name = "machine-learning-for-algorithmic-trading-second-edition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
