name: Monthly Momentum Stocks 

on:
  schedule:
    - cron: "0 20 1 * *" # Runs on the 1st of every month at 8:00 PM UTC
  workflow_dispatch:

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Top 3 Momentum Stocks
        run: python simple_momentum.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
